### ISSUE TITLE
Transition to using Django REST framework based API

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr-up#128]
RSR is moving from tastypie to Django REST framework (DRF) as the framework basis for its API. We will support the old tastypie API for as long as needed, but all, or at least most, new development should happen using DRF.

We are now adding location data to project updates and this requires changes to Up and its communicating with RSR. 

For the reasons above I suggest that the DRF based API be used by Up, at a minimum for the new requirements, but ideally for all API use.

### Overview of new requirements

A project update can now have one or more locations associated with it. At least initially there will only be one location per update, but the underlying models allow for an arbitrary number of locations.

An example of the XML format for posting an update with a location can be found [here](https://gist.github.com/zzgvh/440059b1c7051a527733).

DRF uses header-based authentication, so instead of sending the API key in the query string it should be included in a header as follows:
```text
Authorization: Token <api token>
```
The username is not needed.

### Overview of transition of all of Up to DRF

Ideally all of Up should use the DRF based API. The RSR data is of course the same but the XML is formatted slightly different and thus needs changes in how Up interprets what's sent to it. An example of the XML can be seen [here as a singe update](http://rsr.tmp.akvo-ops.org/rest/v1/project_update/5298/?format=xml) and [here a list of updates](http://rsr.tmp.akvo-ops.org/rest/v1/project_update/?format=xml), but this is only the basic project update resource with the location in-lined.

I don't know exactly what calls Up does against the current tastypie API, so a list of that is needed for me to be able to build out what's needed in DRF.

**Comment by stellanl** [comment]
Only two calls to v1 API remain:
* [] User
* [] Organisation
