### ISSUE TITLE
picture turning 90°

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr-up#133]
Submitted by user: Anonymous

Submitted values are:

First Name
   apollo

   App Version Number

   Android Version Number

   Phone Make & Model

   Feedback Type
  Bug

   Frequency (Bug Occurence / Feature Usage)
  Always

   Title
   picture turning 90°

   Description
  Picture is rotated 90° when uploaded
##    Supporting Files (Screenshots)

Thank you for supporting Open Source by using Webform.com [1]!

[1] http://webform.com/?utm_source=webform.com&amp;utm_medium=email&amp;utm_content=thank+you+for+supporting+open+source&amp;utm_campaign=submission_emails

**Comment by nadiagorchakova** [comment]
I haven't seen any complaints about picture rotated 90 degrees when uploaded, so I'm closing the issue for now.
