### ISSUE TITLE
Translate Up into other languages

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr-up#156]
- [x] French
- [x] Spanish
- [x] Swedish
- [ ] Dutch
- [ ] German

**Comment by stellanl** [comment]
I suggest we settle for the French, Spanish and Swedish (it has less than 10 strings missing) translations for 1.5, and leave Dutch and German for when we can assign some translators.
Who knows about how to update the source in Transifex?

**Comment by stellanl** [comment]
Broke out languages not released in 1.5 to separate issues
