### ISSUE TITLE
How should Up work for unattached users  in RSR 3?

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr-up#159]
As described in akvo/akvo-rsr#1042, RSR 3 users will become enabled upon email verification, but not attached to an organisation. This will need to be adressed in Up, as the current model assumes anyone who can log in is attached to an organisation which determines which projects are visible.

Some possible solutions:
- Prevent unattached users from logging in to Up, and give a helpful error message.
- Let them log in; show no projects but give a helpful hint about when and how they will get more.
- Let them log in and show all projects (this quickly gets resource intensive)

**Comment by adriancollier** [comment]
Thanks for thinking ahead with this Stellan!

I think in the short term the second option is probably the best from a users' point of view.

When we have more time, I would like to see if we could replicate the Employment form we have within MyRSR on Up, so people could apply to be part of an org within the app.

We should at the same time also add the registration form to Up, so for some field partners they could in theory work entirely from the app.

@stellanl any chance you could give us some estimates on:

1. Implementing option 2 above
2. Adding the employment form found here: 
![screen shot 2015-01-23 at 12 04 47](https://cloud.githubusercontent.com/assets/1426234/5873556/0c0cf37c-a2f8-11e4-87f4-62e7eba26b7f.png)
3. Adding the registration process

**Comment by stellanl** [comment]
1. If the Login API remains unchanged, the only thing needed to implement option 2 above is to react to a project count of 0. An hour's work.
2. I assume this requires API additions ( I have not seen the any V3 UI code). 2-3 days, probably.
3. Would this be a registration with or without Email verification?

**Comment by adriancollier** [comment]
Thanks Stellan!

For option 3 this would need to have email verification - I'm guessing this complicates things slightly. 

Some good news I can give though is that the current Employment form that I have pasted above is using the API ( @KasperBrandt can prob give more details if needed).

**Comment by stellanl** [comment]
Ok, have looked at the new API.
2. Yes, the API to request a connection is already in place. To make a nice UI where you can pick your org(s) from a list, we also need to fetch the entire org list. So say 3 days. 4 if the list should be searchable, too.

**Comment by stellanl** [comment]
Solution 2 was included in release 1.4
