### ISSUE TITLE
Forgot password - broken link

### ISSUE THREAD

**Issue by orifito** [akvo/akvo-rsr-up#161]
`Forgot password?` button at the homepage points to old [url](http://rsr.akvo.org/accounts/password/reset/)

**Comment by stellanl** [comment]
True (this is also true for the link on the help page, http://akvo.org/help/help-support/rsr-help/ ).
What is the correct new link? I cannot find it from any login/registration page in rsr.
Should take no more than 5 minutes to fix, of course.

**Comment by stellanl** [comment]
The "I forgot my password" link on the sign_in page was not displayed at all when I had AdBlock Pro activated in Firefox.
