### ISSUE TITLE
Play store must have answers for app rating system

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr-up#170]
To continue to be freely available through Play Store, apps must now declare who they are suitable for (how the data from them are handled; if there are sex and drug references etc).
See https://support.google.com/googleplay/android-developer/answer/188189
Most of the questionnaire answers for Up are obvious, but a few will need some thought.

[] Category could either be Social Network or the catch-all Tools/Productivity/Comms/Other
[] If location data is published/shared with other users. (I am assuming Yes. It is optional and obvious in Up, but these are all Yes/No questions so nuances are lost)
[] If personal data like names is published/shared with other users. Good question as this only happens if a user actually posts an update.
[] If we moderate all shared content to filter out anything disturbing. (Assuming No.)

**Comment by bjelkeman** [comment]
My vote goes as follows:
1. Catch-all
2. Yes
3. Yes
4. No

**Comment by stellanl** [comment]
I so declared the app. Resulting rating seems to let 3-year-olds use it...
