### ISSUE TITLE
Remove dependency on old API

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr-up#187]
We need to fully transition to the REST API, as RSR is planning to stop supporting the old one.

**Comment by KasperBrandt** [comment]
Note on this: The old TastyPie API has been removed as of the latest release. All ```/api/v1/``` requests are now routed through the REST API (but return the same response).

**Comment by stellanl** [comment]
The last use of /api/v1 URLs was removed as part of the Results Framework work.
