### ISSUE TITLE
Scrollable Views change position on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [akvo/akvo-rsr-up#199]
When I perform these sequences of events, the scrollable webview on screen goes back to the top:

1. Click on About
2. Click on License information
3. Orientation Change

**Comment by nadiagorchakova** [comment]
Hi @reverse-unina and thanks for your input! We will review the issue.

**Comment by nadiagorchakova** [comment]
Could not replicate the issue on the app version 1.6.0 @stellanl could you double check?

**Comment by reverse-unina** [comment]
Excuse me, I forgot an event.
The correct sequence is:
1. Click on About
2. Click on License information
3. Scroll Down
4. Orientation Change

Thank you for the feedback

**Comment by stellanl** [comment]
Duplicated on my phone.
But the impact is minimal.
