### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [akvo/akvo-rsr-up#200]
When I perform these sequences of events, the dialog on screen disappears:

Sequence 1
1. Click on Sign In with wrong or null username/password
2. Orientation Change

Sequence 2
1. Press Menu button
2.  Click on Settings
3.  Click on Delete cached pictures
4. Orientation Change

Sequence 3
1. Press Menu button
2.  Click on Settings
3.  Click on Data Server
4. Orientation Change

**Comment by nadiagorchakova** [comment]
Hi @reverse-unina and thanks for your input! We will review the issue.

**Comment by stellanl** [comment]
This is normal; unless you write code to save and restore state, activities are recreated on rotation. They start over from the beginning, before the dialog is shown.

**Comment by reverse-unina** [comment]
Thank you for the quick response.
I am a researcher exploring Android failures. Mobile apps introduce the challenge to handle properly lifecycle events (e.g. orientation change or back button) and it may affect the user experience causing failures on GUI widgets (in this case a dialog) or app crashes.
I am contacting you and other developers to know if the dialog disappearence is an expected behaviour of the app or it is due to the limitations of the Android framework.

Reverse-VinRiccio

**Comment by reverse-unina** [comment]
As regards to dialogs I send you a pointer from Android guidelines.
Source: https://developer.android.com/guide/topics/ui/dialogs.html

The Dialog class is the base class for dialogs, but you should avoid instantiating Dialog directly[...]
[AlertDialog et al.] classes define the style and structure for your dialog, but you should use a **DialogFragment** as a container for your dialog. The DialogFragment class provides all the controls you need to create your dialog and manage its appearance, instead of calling methods on the Dialog object.

Using DialogFragment to manage the dialog ensures that it correctly handles **lifecycle events such as when the user presses the Back button or rotates the screen**.

**Comment by stellanl** [comment]
DialogFragment is only available from API 11. We support API 7.

**Comment by reverse-unina** [comment]
Try to check showDialog()

https://developer.android.com/reference/android/app/Dialog.html
