### ISSUE TITLE
Improve design of Results submission in the app

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr-up#201]
Scope for (rough) design improvement:

- Navigation to Results (investigate possibility to shorten the path to Results update form. right now - three steps)

- Results Update form

- Unify terminology

- History tab (user has to know if someone submitted result update for this indicator period or not)

**Comment by Kiarii** [comment]
https://invis.io/MB9JJ22D9#/209039207_1-_Login
