### ISSUE TITLE
Social media

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr-up#70]
Was just thinking wouldn't it be super cool if you could also share the update you just posted (with the mobile app) via facebook or twitter?

**Comment by nadiagorchakova** [comment]
On RSR website, It's possible to share an update via Fb or Twitter. Should be enabled for the app as well at some point. It might contribute to the exposure of RSR on social media.

That's how it looks on the website (via Twitter): the text is made up of Project name, Update title and mentions a user who posted the update

<img width="1199" alt="screen shot 2017-02-27 at 14 57 21" src="https://cloud.githubusercontent.com/assets/21127166/23363938/56d77786-fcfd-11e6-9678-fc7b2fdf7578.png">
