### ISSUE TITLE
Photos taken not showing up in gallery

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr-up#99]
Tried on the Galaxy S4 and when I take a photo it is not stored in my Gallery anywhere as it says it should be here: https://github.com/akvo/akvo-rsr-mobile/issues/39

**Comment by nadiagorchakova** [comment]
Was able to reproduce the issue - took a photo through RSR Up app and afterwards could not locate that photo in my phone's Gallery.
